name: minecraft
# Use this for DH: https://www.youtube.com/watch?v=jQGYUsasGaM&t=28s

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      VERSION: 1.21.5
      TYPE: FABRIC
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 32
      INIT_MEMORY: 6G
      MAX_MEMORY: 16G
      MOTD: "§l§6Welcome§r nerds..."
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      DIFFICULTY: hard
      RCON_PASSWORD: ${MINECRAFT_RCON_PASSWORD}
      SNOOPER_ENABLED: false
      MODE: survival
      SERVER_NAME: "The Gangs All Here"
      ENABLE_WHITELIST: true
      WHITELIST: ${MINECRAFT_WHITELIST}
      OPS: ${MINECRAFT_OPS}
      DEFAULT_PLAYER_PERMISSION_LEVEL: member
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - minecraft_server_data:/data
      - /storage/data/minecraft-server/plugins:/plugins
      - /storage/data/minecraft-server/mods:/mods

  minecraft-backups:
    image: itzg/mc-backup
    container_name: minecraft-backups
    user: "1000:1000"
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "6h"
      RCON_HOST: mc
      RCON_PASSWORD: ${MINECRAFT_RCON_PASSWORD}
      PRUNE_BACKUPS_DAYS: 14
      PRE_BACKUP_SCRIPT: |
        echo "Backup from $$RCON_HOST to $$DEST_DIR"
      #POST_BACKUP_SCRIPT_FILE: /post-backup.sh
    volumes:
      # mount the same volume used by server, but read-only
      - minecraft_server_data:/data
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - /storage/data/minecraft-server/backups:/backups
      - ./post-backup.sh:/post-backup.sh:ro
    

volumes:
  minecraft_server_data: