# docker-compose.yaml
include:
  #- utils/utils-compose.yaml
  - mediarr/arr-compose.yaml
  - gaming/minecraft-server.yaml
name: services
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /container-configs/nginx-proxy-manager/data:/data
      - ./letsencrypt:/etc/letsencrypt

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - N8N_LOG_LEVEL=debug
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data: