# docker-compose.yaml
include:
  #- utils/utils-compose.yaml
  - mediarr/arr-compose.yaml
name: services
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /container-configs/nginx-proxy-manager/data:/data
      - ./letsencrypt:/etc/letsencrypt

  muse:
    image: ghcr.io/museofficial/muse:latest
    container_name: muse-jukebox
    restart: always
    volumes:
      - /storage-nvme/data/containers/muse:/data
    environment:
      - DISCORD_TOKEN=${MUSE_DISCORD_TOKEN}
      - YOUTUBE_API_KEY=${MUSE_YOUTUBE_API_KEY}
      - SPOTIFY_CLIENT_ID=${MUSE_SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${MUSE_SPOTIFY_CLIENT_SECRET}

volumes:
  portainer_data: